/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { GraphQLUpload } from "graphql-upload";
import { FileUpload } from "src/storage/base/storage.types";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Activity } from "./Activity";
import { ActivityCountArgs } from "./ActivityCountArgs";
import { ActivityFindManyArgs } from "./ActivityFindManyArgs";
import { ActivityFindUniqueArgs } from "./ActivityFindUniqueArgs";
import { CreateActivityArgs } from "./CreateActivityArgs";
import { UpdateActivityArgs } from "./UpdateActivityArgs";
import { DeleteActivityArgs } from "./DeleteActivityArgs";
import { SessionFindManyArgs } from "../../session/base/SessionFindManyArgs";
import { Session } from "../../session/base/Session";
import { Venue } from "../../venue/base/Venue";
import { ActivityService } from "../activity.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Activity)
export class ActivityResolverBase {
  constructor(
    protected readonly service: ActivityService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Activity",
    action: "read",
    possession: "any",
  })
  async _activitiesMeta(
    @graphql.Args() args: ActivityCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Activity])
  @nestAccessControl.UseRoles({
    resource: "Activity",
    action: "read",
    possession: "any",
  })
  async activities(
    @graphql.Args() args: ActivityFindManyArgs
  ): Promise<Activity[]> {
    return this.service.activities(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Activity, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Activity",
    action: "read",
    possession: "own",
  })
  async activity(
    @graphql.Args() args: ActivityFindUniqueArgs
  ): Promise<Activity | null> {
    const result = await this.service.activity(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Activity)
  @nestAccessControl.UseRoles({
    resource: "Activity",
    action: "create",
    possession: "any",
  })
  async createActivity(
    @graphql.Args() args: CreateActivityArgs
  ): Promise<Activity> {
    return await this.service.createActivity({
      ...args,
      data: {
        ...args.data,

        venue: args.data.venue
          ? {
              connect: args.data.venue,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Activity)
  @nestAccessControl.UseRoles({
    resource: "Activity",
    action: "update",
    possession: "any",
  })
  async updateActivity(
    @graphql.Args() args: UpdateActivityArgs
  ): Promise<Activity | null> {
    try {
      return await this.service.updateActivity({
        ...args,
        data: {
          ...args.data,

          venue: args.data.venue
            ? {
                connect: args.data.venue,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Activity)
  @nestAccessControl.UseRoles({
    resource: "Activity",
    action: "delete",
    possession: "any",
  })
  async deleteActivity(
    @graphql.Args() args: DeleteActivityArgs
  ): Promise<Activity | null> {
    try {
      return await this.service.deleteActivity(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Activity)
  async uploadImage(
    @graphql.Args({
      name: "file",
      type: () => GraphQLUpload,
    })
    file: FileUpload,
    @graphql.Args()
    args: ActivityFindUniqueArgs
  ): Promise<Activity> {
    return await this.service.uploadImage(args, file);
  }

  @graphql.Mutation(() => Activity)
  async deleteImage(
    @graphql.Args()
    args: ActivityFindUniqueArgs
  ): Promise<Activity> {
    return await this.service.deleteImage(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Session], { name: "sessions" })
  @nestAccessControl.UseRoles({
    resource: "Session",
    action: "read",
    possession: "any",
  })
  async findSessions(
    @graphql.Parent() parent: Activity,
    @graphql.Args() args: SessionFindManyArgs
  ): Promise<Session[]> {
    const results = await this.service.findSessions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Venue, {
    nullable: true,
    name: "venue",
  })
  @nestAccessControl.UseRoles({
    resource: "Venue",
    action: "read",
    possession: "any",
  })
  async getVenue(@graphql.Parent() parent: Activity): Promise<Venue | null> {
    const result = await this.service.getVenue(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
