/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request, Response } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FileInterceptor } from "@nestjs/platform-express";
import { CharityService } from "../charity.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CharityCreateInput } from "./CharityCreateInput";
import { Charity } from "./Charity";
import { Post } from "../../post/base/Post";
import { CharityFindManyArgs } from "./CharityFindManyArgs";
import { CharityWhereUniqueInput } from "./CharityWhereUniqueInput";
import { CharityUpdateInput } from "./CharityUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CharityControllerBase {
  constructor(
    protected readonly service: CharityService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Charity })
  @nestAccessControl.UseRoles({
    resource: "Charity",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCharity(
    @common.Body() data: CharityCreateInput
  ): Promise<Charity> {
    return await this.service.createCharity({
      data: data,
      select: {
        address: true,
        createdAt: true,
        description: true,
        email: true,
        id: true,
        image: true,
        name: true,
        phone: true,
        suggestedDonation: true,
        updatedAt: true,
        websiteUrl: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Charity] })
  @ApiNestedQuery(CharityFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Charity",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async charities(@common.Req() request: Request): Promise<Charity[]> {
    const args = plainToClass(CharityFindManyArgs, request.query);
    return this.service.charities({
      ...args,
      select: {
        address: true,
        createdAt: true,
        description: true,
        email: true,
        id: true,
        image: true,
        name: true,
        phone: true,
        suggestedDonation: true,
        updatedAt: true,
        websiteUrl: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Charity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Charity",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async charity(
    @common.Param() params: CharityWhereUniqueInput
  ): Promise<Charity | null> {
    const result = await this.service.charity({
      where: params,
      select: {
        address: true,
        createdAt: true,
        description: true,
        email: true,
        id: true,
        image: true,
        name: true,
        phone: true,
        suggestedDonation: true,
        updatedAt: true,
        websiteUrl: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Charity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Charity",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCharity(
    @common.Param() params: CharityWhereUniqueInput,
    @common.Body() data: CharityUpdateInput
  ): Promise<Charity | null> {
    try {
      return await this.service.updateCharity({
        where: params,
        data: data,
        select: {
          address: true,
          createdAt: true,
          description: true,
          email: true,
          id: true,
          image: true,
          name: true,
          phone: true,
          suggestedDonation: true,
          updatedAt: true,
          websiteUrl: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Charity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Charity",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCharity(
    @common.Param() params: CharityWhereUniqueInput
  ): Promise<Charity | null> {
    try {
      return await this.service.deleteCharity({
        where: params,
        select: {
          address: true,
          createdAt: true,
          description: true,
          email: true,
          id: true,
          image: true,
          name: true,
          phone: true,
          suggestedDonation: true,
          updatedAt: true,
          websiteUrl: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Put(":id/image")
  @common.UseInterceptors(FileInterceptor("file"))
  @swagger.ApiConsumes("multipart/form-data")
  @swagger.ApiBody({
    schema: {
      type: "object",

      properties: {
        file: {
          type: "string",
          format: "binary",
        },
      },
    },
  })
  @swagger.ApiParam({
    name: "id",
    type: "string",
    required: true,
  })
  @swagger.ApiCreatedResponse({
    type: Charity,
    status: "2XX",
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async uploadImage(
    @common.Param()
    params: CharityWhereUniqueInput,
    @common.UploadedFile()
    file: Express.Multer.File
  ): Promise<Charity> {
    return this.service.uploadImage(
      {
        where: params,
      },
      Object.assign(file, {
        filename: file.originalname,
      })
    );
  }

  @common.Get(":id/image")
  @swagger.ApiParam({
    name: "id",
    type: "string",
    required: true,
  })
  @swagger.ApiOkResponse({
    type: common.StreamableFile,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async downloadImage(
    @common.Param()
    params: CharityWhereUniqueInput,
    @common.Res({
      passthrough: true,
    })
    res: Response
  ): Promise<common.StreamableFile> {
    const result = await this.service.downloadImage({
      where: params,
    });

    if (result === null) {
      throw new errors.NotFoundException(
        "No resource was found for ",
        JSON.stringify(params)
      );
    }

    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${result.filename}`
    );
    res.setHeader("Content-Type", result.mimetype);
    return result.stream;
  }

  @common.Delete(":id/image")
  @swagger.ApiOkResponse({
    type: Charity,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async deleteImage(
    @common.Param()
    params: CharityWhereUniqueInput
  ): Promise<Charity> {
    return this.service.deleteImage({
      where: params,
    });
  }
}
