/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Charity as PrismaCharity } from "@prisma/client";
import { LocalStorageService } from "src/storage/providers/local/local.storage.service";
import { InputJsonValue } from "src/types";
import { FileDownload, FileUpload } from "src/storage/base/storage.types";
import { LocalStorageFile } from "src/storage/providers/local/local.storage.types";

export class CharityServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly localStorageService: LocalStorageService
  ) {}

  async count(args: Omit<Prisma.CharityCountArgs, "select">): Promise<number> {
    return this.prisma.charity.count(args);
  }

  async charities(args: Prisma.CharityFindManyArgs): Promise<PrismaCharity[]> {
    return this.prisma.charity.findMany(args);
  }
  async charity(
    args: Prisma.CharityFindUniqueArgs
  ): Promise<PrismaCharity | null> {
    return this.prisma.charity.findUnique(args);
  }
  async createCharity(args: Prisma.CharityCreateArgs): Promise<PrismaCharity> {
    return this.prisma.charity.create(args);
  }
  async updateCharity(args: Prisma.CharityUpdateArgs): Promise<PrismaCharity> {
    return this.prisma.charity.update(args);
  }
  async deleteCharity(args: Prisma.CharityDeleteArgs): Promise<PrismaCharity> {
    return this.prisma.charity.delete(args);
  }

  async uploadImage<T extends Prisma.CharityFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CharityFindUniqueArgs>,
    file: FileUpload
  ): Promise<PrismaCharity> {
    file.filename = `profilePicture-${args.where.id}.${file.filename
      .split(".")
      .pop()}`;
    const containerPath = "image";
    const image = await this.localStorageService.uploadFile(
      file,
      [],
      1000000,
      containerPath
    );

    return await this.prisma.charity.update({
      where: args.where,

      data: {
        image: image as InputJsonValue,
      },
    });
  }

  async downloadImage<T extends Prisma.CharityFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CharityFindUniqueArgs>
  ): Promise<FileDownload> {
    const { image } = await this.prisma.charity.findUniqueOrThrow({
      where: args.where,
    });

    return await this.localStorageService.downloadFile(
      image as unknown as LocalStorageFile
    );
  }

  async deleteImage<T extends Prisma.CharityFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CharityFindUniqueArgs>
  ): Promise<PrismaCharity> {
    const { image } = await this.prisma.charity.findUniqueOrThrow({
      where: args.where,
    });

    await this.localStorageService.deleteFile(
      image as unknown as LocalStorageFile
    );

    return await this.prisma.charity.update({
      where: args.where,

      data: {
        image: Prisma.DbNull,
      },
    });
  }
}
