/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Post as PrismaPost } from "@prisma/client";
import { LocalStorageService } from "src/storage/providers/local/local.storage.service";
import { InputJsonValue } from "src/types";
import { FileDownload, FileUpload } from "src/storage/base/storage.types";
import { LocalStorageFile } from "src/storage/providers/local/local.storage.types";

export class PostServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly localStorageService: LocalStorageService
  ) {}

  async count(args: Omit<Prisma.PostCountArgs, "select">): Promise<number> {
    return this.prisma.post.count(args);
  }

  async posts(args: Prisma.PostFindManyArgs): Promise<PrismaPost[]> {
    return this.prisma.post.findMany(args);
  }
  async post(args: Prisma.PostFindUniqueArgs): Promise<PrismaPost | null> {
    return this.prisma.post.findUnique(args);
  }
  async createPost(args: Prisma.PostCreateArgs): Promise<PrismaPost> {
    return this.prisma.post.create(args);
  }
  async updatePost(args: Prisma.PostUpdateArgs): Promise<PrismaPost> {
    return this.prisma.post.update(args);
  }
  async deletePost(args: Prisma.PostDeleteArgs): Promise<PrismaPost> {
    return this.prisma.post.delete(args);
  }

  async uploadImage<T extends Prisma.PostFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PostFindUniqueArgs>,
    file: FileUpload
  ): Promise<PrismaPost> {
    file.filename = `profilePicture-${args.where.id}.${file.filename
      .split(".")
      .pop()}`;
    const containerPath = "image";
    const image = await this.localStorageService.uploadFile(
      file,
      [],
      1000000,
      containerPath
    );

    return await this.prisma.post.update({
      where: args.where,

      data: {
        image: image as InputJsonValue,
      },
    });
  }

  async downloadImage<T extends Prisma.PostFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PostFindUniqueArgs>
  ): Promise<FileDownload> {
    const { image } = await this.prisma.post.findUniqueOrThrow({
      where: args.where,
    });

    return await this.localStorageService.downloadFile(
      image as unknown as LocalStorageFile
    );
  }

  async deleteImage<T extends Prisma.PostFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PostFindUniqueArgs>
  ): Promise<PrismaPost> {
    const { image } = await this.prisma.post.findUniqueOrThrow({
      where: args.where,
    });

    await this.localStorageService.deleteFile(
      image as unknown as LocalStorageFile
    );

    return await this.prisma.post.update({
      where: args.where,

      data: {
        image: Prisma.DbNull,
      },
    });
  }
}
