/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EntityMediaService } from "../entityMedia.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EntityMediaCreateInput } from "./EntityMediaCreateInput";
import { EntityMedia } from "./EntityMedia";
import { Post } from "../../post/base/Post";
import { EntityMediaFindManyArgs } from "./EntityMediaFindManyArgs";
import { EntityMediaWhereUniqueInput } from "./EntityMediaWhereUniqueInput";
import { EntityMediaUpdateInput } from "./EntityMediaUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EntityMediaControllerBase {
  constructor(
    protected readonly service: EntityMediaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EntityMedia })
  @nestAccessControl.UseRoles({
    resource: "EntityMedia",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEntityMedia(
    @common.Body() data: EntityMediaCreateInput
  ): Promise<EntityMedia> {
    return await this.service.createEntityMedia({
      data: data,
      select: {
        createdAt: true,
        entityId: true,
        entityType: true,
        id: true,
        mediaUrl: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [EntityMedia] })
  @ApiNestedQuery(EntityMediaFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "EntityMedia",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async entityMedias(@common.Req() request: Request): Promise<EntityMedia[]> {
    const args = plainToClass(EntityMediaFindManyArgs, request.query);
    return this.service.entityMedias({
      ...args,
      select: {
        createdAt: true,
        entityId: true,
        entityType: true,
        id: true,
        mediaUrl: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EntityMedia })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EntityMedia",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async entityMedia(
    @common.Param() params: EntityMediaWhereUniqueInput
  ): Promise<EntityMedia | null> {
    const result = await this.service.entityMedia({
      where: params,
      select: {
        createdAt: true,
        entityId: true,
        entityType: true,
        id: true,
        mediaUrl: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EntityMedia })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EntityMedia",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEntityMedia(
    @common.Param() params: EntityMediaWhereUniqueInput,
    @common.Body() data: EntityMediaUpdateInput
  ): Promise<EntityMedia | null> {
    try {
      return await this.service.updateEntityMedia({
        where: params,
        data: data,
        select: {
          createdAt: true,
          entityId: true,
          entityType: true,
          id: true,
          mediaUrl: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EntityMedia })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EntityMedia",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEntityMedia(
    @common.Param() params: EntityMediaWhereUniqueInput
  ): Promise<EntityMedia | null> {
    try {
      return await this.service.deleteEntityMedia({
        where: params,
        select: {
          createdAt: true,
          entityId: true,
          entityType: true,
          id: true,
          mediaUrl: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
